[package]
name = "substrate-stellar-sdk"
version = "0.1.0"
authors = ["Torsten Stüber <torsten@satoshipay.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-std = { default-features = false, version = "3.0.0" }
substrate-stellar-xdr = { version = "0.1.4", features=["main-types-only"] }
sodalite = { version = "0.4.0" }  