[package]
name = "substrate-stellar-sdk"
version = "0.1.3"
authors = ["Torsten Stüber <torsten@satoshipay.io>"]
edition = "2018"
license = "Apache-2.0"
description = "A Substrate compatible SDK for Stellar"
repository = "https://github.com/pendulum-chain/substrate-stellar-sdk"
readme = "README.md"
keywords = ["substrate", "Stellar"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-std = { default-features = false, version = "3.0.0" }
substrate-stellar-xdr = { version = "0.2.4" }
sodalite = { version = "0.4.0" }
sha2 = { default-features = false, version = "0.9.5" }
lazy_static = "1.4.0"
base64 = { default-features = false, version = "0.13.0" }